name: Metal Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
        pip install pytest pytest-xdist numpy
        
    - name: Install MLX
      run: |
        pip install mlx>=0.3.0
        
    - name: Install Triton with Metal backend
      run: |
        TRITON_BUILD_WITH_METAL=ON pip install -e .
        
    - name: Run Metal backend tests
      run: |
        pytest -xvs third_party/metal/python/tests/
        
    - name: Run examples
      run: |
        cd third_party/metal/python/examples
        python matmul_example.py --M 1024 --N 1024 --K 1024 --device mps
        python convolution_example.py --batch_size 8 